### ISSUE TITLE
error when run code

### ISSUE THREAD

**Issue by danirub** [Nexmo/php-phone-menu#2]
Fatal error: Uncaught Error: Call to undefined method NexmoDemo\Menu::Action()

**Comment by fabiocflores** [comment]
Hi there. I’m getting the same error:

PHP Fatal error:  Uncaught Error: Call to undefined method NexmoDemo\\Menu::index.php/eventAction() in /var/www/php-phone-menu/public/index.php:15\nStack trace:\n#0 {main}\n  thrown in /var/www/php-phone-menu/public/index.php on line 15

**Comment by lornajane** [comment]
This application uses the path of the request to work out which method to call. We want `\NexmoDemo\Menu\AnswerAction()` but for this to work your application must have its answer URL as `/answer`, relative to the webroot. The errors reported here are similar but different:

The original bug report (which I totally missed, sorry. But I'll answer anyway in case it helps someone else) was for trying to call a method `Action()` which doesn't exist. Check the `nexmo app:update ...` command in the README, this needs to point to `/answer`, rather than just `/` for the app to work.

The second comment calls a method named `index.php/eventAction()` which also doesn't exist. Depending how your webserver is set up, this could be a config problem. You should be able to request `/action` without the `index.php` in it. If you're running locally, the `php -S localhost:8080 ./public/index.php` is the correctly way to start  the webserver.

Hope this helps - I am closing the issue but re-open and post updates if you need anything else!
